stages:
  - build

push release to wow interface:
  image: registry.gitlab.com/jonnynabors/blizzhud_helper
  stage: build
  only:
    - tags
  except:
    - branches
  script:
    - bundle_addon.sh
    - curl -H "x-api-token:$WOW_INTERFACE_TOKEN" https://api.wowinterface.com/addons/update -F "id=$WOW_INTERFACE_PROJECT_NUMBER" -F "version=$CI_COMMIT_TAG" -F "compatible=10.0" -F "updatefile=BlizzHUD_Helper.zip"
  artifacts:
    paths:
      - BlizzHUD_Helper.zip
    expire_in: 1 week

push release to curseforge:
  image: registry.gitlab.com/jonnynabors/blizzhud_helper
  stage: build
  only:
    - tags
  except:
    - branches
  script:
    - bundle_addon.sh
    - curl -H "x-api-token:$CURSEFORGE_TOKEN" https://wow.curseforge.com/api/projects/$CURSEFORGE_PROJECT_ID/upload-file -F metadata="{\"changelog\":\"$CI_COMMIT_TAG_MESSAGE\",\"gameVersions\":[9493,9494],\"releaseType\":\"release\"}" -F displayName="BlizzHUD Helper" -F file=@BlizzHUD_Helper.zip