stages:
  - build

variables:
  WOW_INTERFACE_DEPLOY_JOB: 'curl -H "x-api-token: ${WOW_INTERFACE_TOKEN}" -F "id=8163" -F "version=$CI_COMMIT_TAG" -F "compatible=10.0" -F "updatefile=BlizzHUD_Helper.zip" https://api.wowinterface.com/addons/update'

push release to wow interface:
  image: registry.gitlab.com/jonnynabors/blizzhud_helper
  stage: build
  only:
    - tags
  except:
    - branches
  script:
    - zip BlizzHUD_Helper.zip BlizzHUD_Helper.lua BlizzHUD_Helper.toc
    - echo $WOW_INTERFACE_DEPLOY_JOB
    - $WOW_INTERFACE_DEPLOY_JOB
